name: Android-AAB-FlutterApp

on:
  workflow_dispatch:

jobs:
  build-android-aab:
    name: 📦 Build Android AAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build AAB (Obfuscated)
        run: |
          flutter build appbundle --release \
            --obfuscate \
            --split-debug-info=./build/app/outputs/symbols

      - name: Rename AAB
        run: mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/flutter_app-release.aab

      - name: Upload AAB to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/bundle/release/flutter_app-release.aab
          tag: v1.0.0
          overwrite: true
          body: "Release AAB for Flutter App (obfuscated)"

      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v4.6.2
        with:
          name: debug-symbols
          path: build/app/outputs/symbols/
          if-no-files-found: warn
