name: Android-APK-FlutterApp

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🎉 Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@main
        with:
          channel: stable
          architecture: x64

      - run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build full APK with Obfuscation
        run: |
          flutter build apk --release \
          --obfuscate \
          --split-debug-info=./build/app/outputs/symbols

      - name: Rename APK for upload
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/flutter_app-full.apk

      - name: Upload full APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/flutter_app-full.apk
          tag: v1.0.0
          overwrite: true
          body: "This release includes obfuscated full APK for better security"

      - name: Upload mapping files (for crash debugging)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: debug-symbols
          path: build/app/outputs/symbols/
          if-no-files-found: warn
