name: iOS-Build-FlutterApp

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🍎 Build iOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ipa --no-codesign

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/Runner.ipa
          tag: v1.0.0+1
          overwrite: true
          body: "This is first release"
